# ros_gz_bridge configuration for the left RH8D:
#   ros2 run ros_gz_bridge parameter_bridge --ros-args \
#     -p config_file:=$(ros2 pkg prefix --share seed_rh8d_description)/config/gz_bridge_left.yaml
- gz_topic_name: /clock
  ros_topic_name: /clock
  gz_type_name: gz.msgs.Clock
  ros_type_name: rosgraph_msgs/msg/Clock
  direction: GZ_TO_ROS
- gz_topic_name: rh8d/left/fingertip/thumb/wrench
  ros_topic_name: /rh8d/left/fingertip/thumb/wrench
  gz_type_name: gz.msgs.Wrench
  ros_type_name: geometry_msgs/msg/WrenchStamped
  direction: GZ_TO_ROS
- gz_topic_name: rh8d/left/fingertip/index/wrench
  ros_topic_name: /rh8d/left/fingertip/index/wrench
  gz_type_name: gz.msgs.Wrench
  ros_type_name: geometry_msgs/msg/WrenchStamped
  direction: GZ_TO_ROS
- gz_topic_name: rh8d/left/fingertip/middle/wrench
  ros_topic_name: /rh8d/left/fingertip/middle/wrench
  gz_type_name: gz.msgs.Wrench
  ros_type_name: geometry_msgs/msg/WrenchStamped
  direction: GZ_TO_ROS
- gz_topic_name: rh8d/left/fingertip/ring/wrench
  ros_topic_name: /rh8d/left/fingertip/ring/wrench
  gz_type_name: gz.msgs.Wrench
  ros_type_name: geometry_msgs/msg/WrenchStamped
  direction: GZ_TO_ROS
- gz_topic_name: rh8d/left/fingertip/little/wrench
  ros_topic_name: /rh8d/left/fingertip/little/wrench
  gz_type_name: gz.msgs.Wrench
  ros_type_name: geometry_msgs/msg/WrenchStamped
  direction: GZ_TO_ROS
- gz_topic_name: rh8d/left/palm_ir/scan
  ros_topic_name: /rh8d/left/palm_ir/scan
  gz_type_name: gz.msgs.LaserScan
  ros_type_name: sensor_msgs/msg/LaserScan
  direction: GZ_TO_ROS
- gz_topic_name: /world/rh8d_world/model/rh8d_left/joint_state
  ros_topic_name: /joint_states
  gz_type_name: gz.msgs.Model
  ros_type_name: sensor_msgs/msg/JointState
  direction: GZ_TO_ROS
